

### GET All
GET http://localhost:3000/organize/user

### GET one
GET http://localhost:3000/organize/user/67df079c2b3001c9b12cd6f8

### Criacao de usuario
POST http://localhost:3000/organize/user
Content-Type: application/json

{
    "name": "BoliiinhA",
    "email": "bolinhe@gmail.com",
    "password": "!A12345"
}

###LOGIN
POST http://localhost:3000/organize/user/login
Content-Type: application/json

{
    "email": "bolinha@bolinha.com",
    "password": "novaSenha123"
}
###LOGOUT
POST http://localhost:3000/organize/user/logout
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2N2UxNWIzZGY0N2MwNDk2MDcxODFmNzAiLCJpYXQiOjE3NDI4Mjk0MjgsImV4cCI6MTc0MjgzMzAyOH0.3by--txpBuyAKNwVBh_6i_RpwRJedi0iwNiDddlI5CQ
###
DELETE http://localhost:3000/organize/user/67e15b3df47c049607181f70

### PUT DE USUARIO
PUT http://localhost:3000/organize/user/67df079c2b3001c9b02cd6f8
Content-Type: application/json

{
    "name": "Bolinhs",
    "email": "bolinha@bo.com"
}

### Alterar senha
PATCH http://localhost:3000/organize/user/password-update
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2N2UxOGUxNjk4Y2E5YjBkNDQ0NWFkMzAiLCJpYXQiOjE3NDI4MzU1MTEsImV4cCI6MTc0MjgzOTExMX0.IjQdlJp7Ww8S9z3g6Vdh_iBVNP_Ui-brk80sPkFP-58
Content-Type: application/json

{
    "oldPassword": "novaSenha123",
    "newPassword": "novaSenha123"
}