GET http://localhost:3000/organize/user
###

GET http://localhost:3000/organize/user/67df079c2b3001c9b12cd6f8

###

POST http://localhost:3000/organize/user
Content-Type: application/json

{
    "name": "Boliiinheerrrs",
    "email": "bolinha@bolinha.com",
    "password": "123456"
}

###

POST http://localhost:3000/organize/user/login
Content-Type: application/json

{
    "email": "bolinha@bolinha.com",
    "password": "123456"
}

###
DELETE http://localhost:3000/organize/user/67e15b60f47c049607181f73

###

PUT http://localhost:3000/organize/user/67df079c2b3001c9b02cd6f8
Content-Type: application/json

{
    "name": "Bolinhs",
    "email": "bolinha@bo.com"
}